CREATE TABLE tbl_Users(userID INTEGER PRIMARY KEY AUTOINCREMENT,userName TEXT,salt TEXT,passwordSec TEXT,admin INTEGER);
CREATE TABLE tbl_Student(studentID INTEGER PRIMARY KEY AUTOINCREMENT,surname TEXT,forename TEXT,regGroup TEXT,gender TEXT,examNumber INTEGER,pupilPremium INTEGER,eal INTEGER,catMean INTEGER,catVerbal INTEGER,catNonVerbal INTEGER,catQuant INTEGER,catAverage INTEGER);
CREATE TABLE tbl_Sen(senID INTEGER PRIMARY KEY AUTOINCREMENT,senName TEXT,senShort TEXT);
CREATE TABLE tbl_StudentSen (studentID INTEGER,senID INTEGER,PRIMARY KEY(studentID, senID),FOREIGN KEY(studentID) REFERENCES tbl_Student(studentID),FOREIGN KEY(senID) REFERENCES tbl_Sen(senID));
CREATE TABLE tbl_Allergy(allergyID INTEGER PRIMARY KEY AUTOINCREMENT,allergyName TEXT);
CREATE TABLE tbl_StudentAllergy(studentID INTEGER,allergyID INTEGER,PRIMARY KEY (studentID, allergyID),FOREIGN KEY (studentID) REFERENCES tbl_Student(studentID),FOREIGN KEY (allergyID) REFERENCES tbl_Allergy(allergyID));
CREATE TABLE tbl_Group(groupID INTEGER PRIMARY KEY AUTOINCREMENT,groupName TEXT);
CREATE TABLE tbl_StudentGroup(groupID INTEGER,studentID INTEGER,PRIMARY KEY (groupID, studentID),FOREIGN KEY (groupID) REFERENCES tbl_Group(groupID),FOREIGN KEY (studentID) REFERENCES tbl_Student(studentID));
CREATE TABLE tbl_Course(courseID INTEGER PRIMARY KEY AUTOINCREMENT,courseName TEXT);
CREATE TABLE tbl_CourseGroup(courseID INTEGER,groupID INTEGER,PRIMARY KEY (courseID, groupID),FOREIGN KEY (courseID) REFERENCES tbl_Course(courseID),FOREIGN KEY (groupID) REFERENCES tbl_Group(groupID));
CREATE TABLE tbl_StudentCourse ( studentID INTEGER, courseID INTEGER, targetGrade TEXT, PRIMARY KEY(studentID,courseID), FOREIGN KEY(studentID) REFERENCES tbl_Student(studentID), FOREIGN KEY(courseID) REFERENCES tbl_Course(courseID) );
CREATE TABLE tbl_Module(moduleID INTEGER PRIMARY KEY AUTOINCREMENT,moduleName TEXT,courseID INTEGER,FOREIGN KEY (courseID) REFERENCES tbl_Course(courseID));
CREATE TABLE tbl_StudentModuleResult(studentID INTEGER,moduleID INTEGER,results INTEGER,PRIMARY KEY (studentID, moduleID),FOREIGN KEY (studentID) REFERENCES tbl_Student(studentID),FOREIGN KEY (moduleID) REFERENCES tbl_Module(moduleID));