INSERT INTO tbl_Sen(senName, senShort) VALUES ('Specific Learning Difficulty', 'SPLD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Moderate Learning Difficulty','MLD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Severe Learning Difficulty','SLD');	
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Profound & Multiple Learning Difficulty','PMLD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Social, Emotional and Mental Health','SEMH');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Speech, Language and Communication Needs','SLCN');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Hearing Impairment','HI');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Visual Impairment', 'VI');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Multi-Sensory Impairment','MSI');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Physical Disability','PD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Autistic Spectrum Disorder','ASD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Other Difficulty/Disability','OTH');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('support but no specialist assessment of type of need', 'NSA SEN');

INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('BALL','Jess','11PBR','FEMALE',0,0,115,113,116,117);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('BEBBINGTON','Thomas','11BMA','MALE',0,0,85,92,79,83);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('CHOUDHURY','Alisha','11SDE','FEMALE',0,0,105,106,112,96);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('CHRISTMAS','Ryan','11BMA','MALE',0,0,93,90,90,100);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('COOK','George','11SDE','MALE',0,0,111,114,108,112);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('CROWTHER','Kezia','11LFA','FEMALE',0,0,116,125,114,108);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('DOYLE-MCHARG','Jade','11LFA','FEMALE',0,0,111,119,112,103);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('HALL','Trevannah','11KBU','FEMALE',0,0,,,,);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('HUNT','Phoebe','11BMA','FEMALE',0,0,114,115,120,108);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('JACKSON','Evie','11NPH','FEMALE',0,0,120,115,124,122);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('LOCK','George','11SDE','MALE',0,0,96,95,92,102);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('MAXWELL','Sinead','11CLA','FEMALE',1,0,,,,);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('MCCORD','Emily','11BMA','FEMALE',0,0,118,119,114,120);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('NEWTON','Jake','11KBU','MALE',1,0,103,107,108,93);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('NOON','Maya','11CLA','FEMALE',0,0,95,103,93,90);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('OKEEFFE','Paris','11SDE','FEMALE',0,0,103,104,96,109);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('QUICK','Leon','11KBU','MALE',0,0,,,,);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('REES','Isobel','11CLA','FEMALE',0,0,122,126,115,124);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('SETCHFIELD','Abi','11BMA','FEMALE',0,0,102,114,96,96);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant) VALUES ('TATE','Alfie','11SDE','MALE',1,0,94,101,87,93);
