INSERT INTO tbl_Sen(senName, senShort) VALUES ('Specific Learning Difficulty', 'SPLD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Moderate Learning Difficulty','MLD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Severe Learning Difficulty','SLD');	
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Profound & Multiple Learning Difficulty','PMLD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Social, Emotional and Mental Health','SEMH');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Speech, Language and Communication Needs','SLCN');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Hearing Impairment','HI');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Visual Impairment', 'VI');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Multi-Sensory Impairment','MSI');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Physical Disability','PD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Autistic Spectrum Disorder','ASD');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('Other Difficulty/Disability','OTH');
INSERT INTO tbl_Sen(senName, senShort) VALUES ('support but no specialist assessment of type of need', 'NSA SEN');

INSERT INTO tbl_Allergy(allergyName) VALUES ('Diabetic');
INSERT INTO tbl_Allergy(allergyName) VALUES ('Penuts');
INSERT INTO tbl_Allergy(allergyName) VALUES ('Gluten');
INSERT INTO tbl_Allergy(allergyName) VALUES ('Celery');
INSERT INTO tbl_Allergy(allergyName) VALUES ('Lactose Intolerant');
INSERT INTO tbl_Allergy(allergyName) VALUES ('Soy');
INSERT INTO tbl_Allergy(allergyName) VALUES ('Shellfish');
INSERT INTO tbl_Allergy(allergyName) VALUES ('Eggs');


INSERT INTO tbl_Group(groupName) VALUES ('11C PSYCH');

INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,1);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,2);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,3);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,4);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,5);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,6);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,7);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,8);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,9);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,10);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,11);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,12);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,13);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,14);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,15);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,16);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,17);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,18);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,19);
INSERT INTO tbl_StudentGroup(groupID, studentID) VALUES (1,20);

INSERT INTO tbl_Course(courseName) VALUES ('BTEC Psychology');

INSERT INTO tbl_Module(moduleName) VALUES ('Memory');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,1);
INSERT INTO tbl_Module(moduleName) VALUES ('NVC');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,2);
INSERT INTO tbl_Module(moduleName) VALUES ('Personality');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,3);
INSERT INTO tbl_Module(moduleName) VALUES ('Stereotyping');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,4);
INSERT INTO tbl_Module(moduleName) VALUES ('Research Methods');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,5);
INSERT INTO tbl_Module(moduleName) VALUES ('Social Conformity');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,6);
INSERT INTO tbl_Module(moduleName) VALUES ('Sex and Gender');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,7);
INSERT INTO tbl_Module(moduleName) VALUES ('Aggression');
INSERT INTO tbl_CourseModule(courseID, moduleID) VALUES (1,8);

INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('BALL','Jess','11PBR','FEMALE',2011,0,0,115,113,116,117,33);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('BEBBINGTON','Thomas','11BMA','MALE',2016,0,0,85,92,79,83,22);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('CHOUDHURY','Alisha','11SDE','FEMALE',2033,0,0,105,106,112,96,27);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('CHRISTMAS','Ryan','11BMA','MALE',2035,0,0,93,90,90,100,27);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('COOK','George','11SDE','MALE',2039,0,0,111,114,108,112,30);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('CROWTHER','Kezia','11LFA','FEMALE',2047,0,0,116,125,114,108,30);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('DOYLE-MCHARG','Jade','11LFA','FEMALE',2052,0,0,111,119,112,103,28);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('HALL','Trevannah','11KBU','FEMALE',2078,0,0,0,0,0,0,30);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('HUNT','Phoebe','11BMA','FEMALE',2091,0,0,114,115,120,108,31);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('JACKSON','Evie','11NPH','FEMALE',2094,0,0,120,115,124,122,33);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('LOCK','George','11SDE','MALE',2111,0,0,96,95,92,102,30);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('MAXWELL','Sinead','11CLA','FEMALE',2117,1,0,0,0,0,0,21);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('MCCORD','Emily','11BMA','FEMALE',2118,0,0,118,119,114,120,33);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('NEWTON','Jake','11KBU','MALE',2132,1,0,103,107,108,93,27);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('NOON','Maya','11CLA','FEMALE',2134,0,0,95,103,93,90,27);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('OKEEFFE','Paris','11SDE','FEMALE',2135,0,0,103,104,96,109,30);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('QUICK','Leon','11KBU','MALE',2144,0,0,0,0,0,0,27);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('REES','Isobel','11CLA','FEMALE',2146,0,0,122,126,115,124,33);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('SETCHFIELD','Abi','11BMA','FEMALE',2154,0,0,102,114,96,96,30);
INSERT INTO tbl_Student(surname,forename,regGroup,gender,examNumber,pupilPremium,eal,catMean,catVerbal,catNonVerbal,catQuant,catAverage) VALUES ('TATE','Alfie','11SDE','MALE',2172,1,0,94,101,87,93,28);

INSERT INTO tbl_StudentAllergy(studentID, allergyID) VALUES (2,2);
INSERT INTO tbl_StudentAllergy(studentID, allergyID) VALUES (5,1);
INSERT INTO tbl_StudentAllergy(studentID, allergyID) VALUES (6,5);
INSERT INTO tbl_StudentAllergy(studentID, allergyID) VALUES (9,4);
INSERT INTO tbl_StudentAllergy(studentID, allergyID) VALUES (12,7);
INSERT INTO tbl_StudentAllergy(studentID, allergyID) VALUES (15,3);

INSERT INTO tbl_StudentSEN(studentID, senID) VALUES (1,3);
INSERT INTO tbl_StudentSEN(studentID, senID) VALUES (5,8);
INSERT INTO tbl_StudentSEN(studentID, senID) VALUES (14,6);
INSERT INTO tbl_StudentSEN(studentID, senID) VALUES (14,7);
INSERT INTO tbl_StudentSEN(studentID, senID) VALUES (20,1);


INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,1,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,2,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,3,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,4,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,5,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,6,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,7,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (1,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (2,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (3,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (4,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (5,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (6,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (7,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (8,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (9,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (10,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (11,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (12,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (13,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (14,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (15,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (16,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (17,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (18,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (19,8,0);
INSERT INTO tbl_StudentModuleResult(studentID,moduleID,results) VALUES (20,8,0);

